# Generated by Django 5.2.7 on 2025-12-04 05:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=100)),
                ('price_per_sqm', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amenity_type', models.CharField(choices=[('Basic', 'Basic'), ('Luxury', 'Luxury')], default='Basic', max_length=6)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_amenities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('property_address', models.CharField(max_length=1000)),
                ('property_size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_bedrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_bathrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_img', models.ImageField(upload_to='propertyimg/')),
                ('type', models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Rent'), ('LEASE', 'For Lease'), ('FORECLOSURE', 'Foreclosure')], max_length=12)),
                ('is_available_for_tour', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('UNDER_REVIEW', 'Under Review')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
                ('property_municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='listings.municipality')),
            ],
        ),
    ]
