# Generated by Django 5.2.7 on 2025-12-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_tours',
            field=models.ManyToManyField(blank=True, related_name='properties_on_tour', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='listings.property'),
        ),
    ]
