# Generated by Django 5.2.7 on 2025-12-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_property_property_img_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Properties'},
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='is_primary',
            new_name='is_main',
        ),
    ]
