# Generated by Django 5.2.7 on 2025-12-04 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_amenity_options_alter_municipality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
