# Generated by Django 5.2.7 on 2025-12-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_record', to='listings.property'),
        ),
        migrations.AddField(
            model_name='commission',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.sale'),
        ),
    ]
