# Generated by Django 5.2.7 on 2025-12-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_sale_discount_amount_sale_original_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='original_list_price',
        ),
    ]
