# Generated by Django 5.2.7 on 2026-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_property_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_tours',
        ),
    ]
