# Generated by Django 5.2.7 on 2026-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_property_property_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15),
        ),
    ]
