# Generated by Django 5.2.7 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="requested_role",
            field=models.CharField(
                blank=True,
                choices=[("Buyer", "Buyer"), ("Agent", "Agent"), ("Owner", "Owner")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role_request_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]

