# Generated by Django 5.2.7 on 2026-04-24 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_userprofile_role_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('HOUSE_AND_LOT', 'House and Lot'), ('LOT', 'Lot'), ('APARTMENT', 'Apartment'), ('CONDO', 'Condo'), ('COMMERCIAL_SPACE', 'Commercial Space')], default='HOUSE_AND_LOT', max_length=20),
        ),
    ]
