# Generated by Django 5.2.7 on 2026-04-25 17:35

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_property_building_size_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, default='propertyimg/default.jpg', upload_to=listings.models.property_image_upload_path),
        ),
    ]
