# Generated by Django 5.2.7 on 2026-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_propertyimage_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New/Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor/Needs Renovation')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='location_quality',
            field=models.CharField(choices=[('PREMIUM', 'Premium (CBD/Elite)'), ('URBAN', 'Urban (Central)'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural')], default='SUBURBAN', max_length=20),
        ),
    ]
