# Generated by Django 5.2.7 on 2026-04-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_smart_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-tour_datetime']},
        ),
    ]
