# Generated by Django 5.2.7 on 2026-04-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0006_sale_admin_notes_sale_approval_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commission",
        ),
    ]

