# Generated by Django 5.2.7 on 2026-02-19 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0006_alter_property_property_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('THRESHOLD', 'Threshold Deviation'), ('GRIEFING', 'Anti-Griefing')], max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_flags', to='listings.property')),
            ],
        ),
    ]
